import { Patrick_Hand } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/reduxProvider";
import NavBar from "@/components/topbar/navBar";

const patrick = Patrick_Hand({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${patrick.className} tracking-wide antialiased  scroll-smooth`}
      >
        <ReduxProvider>
          <div className="fixed top-0 left-0 w-full z-50 bg-neutral-100/30 shadow-md p-4 ">
            <NavBar />
          </div>

          <div className="text-rose-950 p-4">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
